version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: todo-backend
    container_name: todo_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000