version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: todo-backend
    container_name: todo_backend
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend/todo:/app/todo
      - ./backend/tests:/app/tests
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:13.5
    container_name: todo_postgres
    environment:
        - POSTGRES_USER=todo
        - POSTGRES_PASSWORD=todo
        - POSTGRES_DB=todo
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - 5432:5432
volumes:
  postgres-data: